name: Deploy to github pages
on:
  push:
    branches:
      - master

permissions: read-all|write-all

jobs:
  gh-pages-deploy:
    name: Deploying to gh-pages
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js for use with actions
        uses: actions/setup-node@v3
        with:
          node-version:  19
      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - uses: fregante/setup-git-user@v2
      - name: Run deploy script
        run: npm run gh-pages-deploy
